RockyShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RockyShop.Utility.Interfaces;
using RockyShop.Model.ViewModels;
using RockyShop.Utility.Services;
using System.Security.Claims;
using RockyShop.DataAccess.Repository.Interfaces;
using RockyShop.Model.Models;
using RockyShop.Utility.Utilities;
using NuGet.Versioning;
using RockyShop.Model.Enums;
using Braintree;

namespace RockyShop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IAppUserRepository _appUserRepo;
        private readonly IProductRepository _productRepo;
        private readonly IInquiryHeaderRepository _inquiryHeaderRepo;
        private readonly IInquiryDetailsRepository _inquiryDetailsRepo;
        private readonly IOrderHeaderRepository _orderHeaderRepo;
        private readonly IOrderDetailsRepository _orderDetailsRepo;
        private readonly ShoppingCartService _shoppingCartService;
        private readonly IBraintreeService _braintreeService;
        private readonly IEmailSenderService _emailSenderService;

        public CartController(IAppUserRepository appUserRepo,
            IProductRepository productRepo,
            IInquiryHeaderRepository inquiryHeaderRepo,
            IInquiryDetailsRepository inquiryDetailsRepo,
            IOrderHeaderRepository orderHeaderRepo,
            IOrderDetailsRepository orderDetailsRepo,
            ShoppingCartService shoppingCartService,
            IBraintreeService braintreeService,
            IEmailSenderService emailSenderService)
        {
            _appUserRepo = appUserRepo;
            _productRepo = productRepo;
            _inquiryHeaderRepo = inquiryHeaderRepo;
            _inquiryDetailsRepo = inquiryDetailsRepo;
            _shoppingCartService = shoppingCartService;
            _orderHeaderRepo = orderHeaderRepo;
            _orderDetailsRepo = orderDetailsRepo;
            _braintreeService = braintreeService;
            _emailSenderService = emailSenderService;
        }

        [BindProperty]
        public CartUserVM CartUserVM { get; set; }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_shoppingCartService.GetProductsInCart());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateCart(IEnumerable<ProductInCart> productInCartList)
        {
            UpdateCartState(productInCartList);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Continue(IEnumerable<ProductInCart> productInCartList)
        {
            UpdateCartState(productInCartList);
            return RedirectToAction(nameof(Summary));
        }

        [HttpGet]
        public async Task<IActionResult> Summary()
        {
            AppUser appUser;
            if (User.IsInRole(Constants.AdminRole))
            {
                if (_shoppingCartService.IsCartFromInquiry)
                {
                    InquiryHeader inquiryHeader = _inquiryHeaderRepo.Find(_shoppingCartService.InquiryId);
                    if (inquiryHeader == null)
                        return NotFound();
                    appUser = new AppUser()
                    {
                        Email = inquiryHeader.Email,
                        FullName = inquiryHeader.FullName,
                        PhoneNumber = inquiryHeader.PhoneNumber,
                    };
                }
                else
                {
                    appUser = new AppUser();
                }

                ViewBag.ClientToken = await _braintreeService.GetClientTokenAsync();
            }
            else
            {
                var username = User.FindFirst(ClaimTypes.NameIdentifier);
                appUser = _appUserRepo.Find(username.Value);
            }

            CartUserVM = new CartUserVM()
            {
                ProductInCartList = _shoppingCartService.GetProductsInCart(),
                User = appUser,
            };
            return View(model:CartUserVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(IFormCollection formCollection)
        {
            if (User.IsInRole(Constants.AdminRole))
            {
                return await SubmitOrder(formCollection);
            }
            else
            {
                return await SubmitInquiry();
            }
        }

        [HttpGet]
        public IActionResult InquiryConfirmation(int id)
        {
            if (id != 0)
                return View(_orderHeaderRepo.Find(id));
            return View();
        }

        [HttpGet]
        public IActionResult Remove(int? id)
        {
            if (id == null)
                return NotFound();
            _shoppingCartService.RemoveFromCart((int)id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult ClearCart()
        {
            _shoppingCartService.ResetCart();
            return RedirectToAction(nameof(Index));
        }

        private async Task<IActionResult> SubmitInquiry()
        {
            _shoppingCartService.ClearCartItems();

            //Restore products from db by id
            IEnumerable<int> productIds = CartUserVM.ProductInCartList
                .Select(p => p.Product.Id);
            CartUserVM.ProductInCartList = _productRepo
                .GetAll(filter: p => productIds.Contains(p.Id))
                .Select(p => new ProductInCart() { Product = p })
                .ToList();

            var inquiryHeader = new InquiryHeader()
            {
                AppUserId = HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier),
                InquiryTime = DateTime.Now,
                Email = CartUserVM.User.Email,
                PhoneNumber = CartUserVM.User.PhoneNumber,
                FullName = CartUserVM.User.FullName,
            };
            _inquiryHeaderRepo.Add(inquiryHeader);
            _inquiryHeaderRepo.SaveChanges();

            foreach (var productInCart in CartUserVM.ProductInCartList)
            {
                var inquiryDetails = new InquiryDetails()
                {
                    InquiryHeaderId = inquiryHeader.Id,
                    ProductId = productInCart.Product.Id,
                };
                _inquiryDetailsRepo.Add(inquiryDetails);
            }
            _inquiryDetailsRepo.SaveChanges();

            await _emailSenderService.SendInquiryConfirmationEmailAsync(CartUserVM);

            return RedirectToAction(nameof(InquiryConfirmation));
        }

        private async Task<IActionResult> SubmitOrder(IFormCollection formCollection)
        {
            _shoppingCartService.ResetCart();

            IEnumerable<int> productIds = CartUserVM.ProductInCartList.Select(p => p.Product.Id);
            IEnumerable<Product> products = _productRepo.GetAll(p => productIds.Contains(p.Id));
            foreach (var productInCart in CartUserVM.ProductInCartList)
            {
                productInCart.Product = products.First(p => p.Id == productInCart.Product.Id);
            }
            
            var orderHeader = new OrderHeader()
            {
                CreatedByUserId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value,
                OrderDate = DateTime.Now,
                OrderStatus = OrderStatus.Pending,
                FinalOrderTotal = CartUserVM.ProductInCartList.Sum(p => p.SqFt * p.Product.Price),
                FullName = CartUserVM.User.FullName,
                PhoneNumber = CartUserVM.User.PhoneNumber,
                Email = CartUserVM.User.Email,
                City = CartUserVM.User.City,
                State = CartUserVM.User.State,
                Street = CartUserVM.User.Street,
                PoastalCode = CartUserVM.User.PoastalCode,
            };
            _orderHeaderRepo.Add(orderHeader);
            _orderHeaderRepo.SaveChanges();

            foreach (var productInCart in CartUserVM.ProductInCartList)
            {
                var orderDetails = new OrderDetails()
                {
                    OrderHeaderId = orderHeader.Id,
                    ProductId = productInCart.Product.Id,
                    SqFt = productInCart.SqFt,
                    PricePerSqFt = productInCart.Product.Price,
                };
                _orderDetailsRepo.Add(orderDetails);
            };
            _orderDetailsRepo.SaveChanges();

            string nonce = formCollection["payment_method_nonce"];
            await _braintreeService.ProcessTransactionAsync(orderHeader, nonce);
            _orderHeaderRepo.SaveChanges();

            return RedirectToAction(nameof(InquiryConfirmation), new { id = orderHeader.Id });
        }

        private void UpdateCartState(IEnumerable<ProductInCart> productInCartList)
        {
            _shoppingCartService.ClearCartItems();
            _shoppingCartService.AddToCartRange(productInCartList);
        }
    }
}

RockyShop/Controllers/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RockyShop.DataAccess.Repository.Interfaces;
using RockyShop.Model.Models;
using RockyShop.Model.ViewModels;
using RockyShop.Utility.Services;
using RockyShop.Utility.Utilities;

namespace RockyShop.Controllers
{
    [Authorize(Roles = Constants.AdminRole)]
    public class InquiryController : Controller
    {
        private readonly IInquiryHeaderRepository _inquiryHeaderRepo;
        private readonly IInquiryDetailsRepository _inquiryDetailsRepo;
        private readonly ShoppingCartService _shoppingCartService;

        public InquiryController(IInquiryHeaderRepository inquiryHeaderRepo,
            IInquiryDetailsRepository inquiryDetailsRepo,
            ShoppingCartService shoppingCartService)
        {
            _inquiryHeaderRepo = inquiryHeaderRepo;
            _inquiryDetailsRepo = inquiryDetailsRepo;
            _shoppingCartService = shoppingCartService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            InquiryVM inquiryVM;
            try
            {
                inquiryVM = GetInquiryVM(id);
            }
            catch
            {
                return NotFound();
            }
            return View(inquiryVM);
        }

        [HttpPost]
        [ActionName("Details")]
        [ValidateAntiForgeryToken]
        public IActionResult ConvertToCart(InquiryVM inquiryVM)
        {
            inquiryVM.InquiryDetailsList = _inquiryDetailsRepo
                .GetAllIncludeProduct(d => d.InquiryHeaderId == inquiryVM.InquiryHeader.Id, isTracking: false);
            var products = inquiryVM.InquiryDetailsList
                .Select(d => d.Product);
            _shoppingCartService.ClearCartItems();
            _shoppingCartService.AddToCartRange(products);
            _shoppingCartService.InquiryId = inquiryVM.InquiryHeader.Id;
            return RedirectToAction(controllerName: "Cart", actionName: "Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            InquiryVM inquiryVM;
            try
            {
                inquiryVM = GetInquiryVM(id);
            }
            catch
            {
                return NotFound();
            }
            _inquiryHeaderRepo.Remove(inquiryVM.InquiryHeader);
            _inquiryDetailsRepo.RemoveRange(inquiryVM.InquiryDetailsList);
            _inquiryDetailsRepo.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private InquiryVM GetInquiryVM(int id)
        {
            InquiryHeader inquiryHeader = _inquiryHeaderRepo.Find(id);
            if (inquiryHeader == null)
                throw new ApplicationException();
            IEnumerable<InquiryDetails> inquiryDetailsList = _inquiryDetailsRepo
                .GetAllIncludeProduct(d => d.InquiryHeaderId == inquiryHeader.Id, isTracking: false);
            return new InquiryVM()
            {
                InquiryHeader = inquiryHeader,
                InquiryDetailsList = inquiryDetailsList,
            };
        }

        #region API CALLS

        public IActionResult GetAllInquires()
        {
            return Json(new { data = _inquiryHeaderRepo.GetAll(isTracking: false) });
        }

        #endregion
    }
}

RockyShop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RockyShop.DataAccess.Repository.Interfaces;
using RockyShop.Model.Enums;
using RockyShop.Model.Models;
using RockyShop.Model.ViewModels;
using RockyShop.Utility.Interfaces;
using RockyShop.Utility.Utilities;
using System.Linq.Expressions;

namespace RockyShop.Controllers
{
    [Authorize(Roles = Constants.AdminRole)]
    public class OrderController : Controller
    {
        private readonly IOrderHeaderRepository _orderHeaderRepo;
        private readonly IOrderDetailsRepository _orderDetailsRepo;
        private readonly IBraintreeService _braintreeService;

        public OrderController(IOrderHeaderRepository orderHeaderRepo,
            IOrderDetailsRepository orderDetailsRepo,
            IBraintreeService braintreeService)
        {
            _orderDetailsRepo = orderDetailsRepo;
            _orderHeaderRepo = orderHeaderRepo;
            _braintreeService = braintreeService;
        }

        [HttpGet]
        public IActionResult Index(int? searchStatus, string searchName = "", string searchEmail = "", string searchPhone = "")
        {
            Expression<Func<OrderHeader, bool>> filter =
                o => o.FullName.Contains(searchName) && o.Email.Contains(searchEmail) && o.PhoneNumber.Contains(searchPhone);
            if(searchStatus != null)
            {
                Expression<Func<OrderHeader, bool>> searchStatusFilter = o => o.OrderStatus == (OrderStatus)searchStatus;
                filter = CombineFilters(filter, searchStatusFilter);
            }
            var viewModel = new OrderIndexVM()
            {
                OrderHeaders = _orderHeaderRepo.GetAll(filter),
                StatusSelectList = Enum.GetValues<OrderStatus>()
                    .Select(os => new SelectListItem()
                    {
                        Value = ((int)os).ToString(),
                        Text = os.ToString(),
                    }),
            };
            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            OrderHeader orderHeader = _orderHeaderRepo.Find(id);
            if (orderHeader == null)
                return NotFound();
            var viewModel = new OrderDetailsVM()
            {
                OrderHeader = orderHeader,
                OrderDetailsList = _orderDetailsRepo.GetAllIncludeAll(d => d.OrderHeaderId == orderHeader.Id, isTracking: false),
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult StartProcessing(OrderDetailsVM viewModel)
        {
            OrderHeader orderHeader = _orderHeaderRepo.Find(viewModel.OrderHeader.Id);
            if (orderHeader == null)
                return NotFound();
            orderHeader.OrderStatus = OrderStatus.Processing;
            _orderHeaderRepo.SaveChanges();
            return RedirectToAction(nameof(Details), new {id = orderHeader.Id} );
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ShipOrder(OrderDetailsVM viewModel)
        {
            OrderHeader orderHeader = _orderHeaderRepo.Find(viewModel.OrderHeader.Id);
            if (orderHeader == null)
                return NotFound();
            orderHeader.OrderStatus = OrderStatus.Shipped;
            orderHeader.ShippingDate = DateTime.Now;
            _orderHeaderRepo.SaveChanges();
            return RedirectToAction(nameof(Details), new { id = orderHeader.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CancelOrder(OrderDetailsVM viewModel)
        {
            OrderHeader orderHeader = _orderHeaderRepo.Find(viewModel.OrderHeader.Id);
            if (orderHeader == null)
                return NotFound();
            if(orderHeader.OrderStatus != OrderStatus.Refunded || orderHeader.OrderStatus != OrderStatus.Cancelled)
                orderHeader.OrderStatus = await _braintreeService.RefundAsync(orderHeader);
            _orderHeaderRepo.SaveChanges();
            return RedirectToAction(nameof(Details), new { id = orderHeader.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateOrderDetails(OrderDetailsVM viewModel)
        {
            OrderHeader orderHeader = _orderHeaderRepo.FirstOrDefault(o => o.Id == viewModel.OrderHeader.Id, isTracking: false);
            if (orderHeader == null)
                return NotFound();
            if (ModelState.IsValid)
                _orderHeaderRepo.Update(viewModel.OrderHeader);
            _orderHeaderRepo.SaveChanges();
            return RedirectToAction(nameof(Details), new { id = orderHeader.Id });
        }

        private Expression<Func<OrderHeader, bool>> CombineFilters(
            Expression<Func<OrderHeader, bool>> first,
            Expression<Func<OrderHeader, bool>> second)
        {
            var toInvoke = Expression.Invoke(second, first.Parameters);
            return Expression.Lambda<Func<OrderHeader, bool>>(Expression.AndAlso(first.Body, toInvoke), first.Parameters);
        }
    }
}

RockyShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using RockyShop.Utility.Utilities;
@using RockyShop.Utility.Services
@inject ShoppingCartService ShoppingCartService

<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RockyShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">*@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RockyShop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    @*<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet"/>*@
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css"/>
     <!-- Syncfusion ASP.NET Core controls styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/21.1.35/fluent.css" />

</head>
<body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/tile.png" width="50%"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Catalog</a>
                        </li>
                        @if (User.IsInRole(Constants.AdminRole))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" asp-controller="Product" asp-action="Index">Products</a></li>
                                  <li><div class="dropdown-divider"></div></li>
                                  <li><a class="dropdown-item" asp-controller="Category" asp-action="Index">Categories</a></li>
                                  <li><a class="dropdown-item" asp-controller="ApplicationType" asp-action="Index">Application Types</a></li>
                                  <li><div class="dropdown-divider"></div></li>
                                  <li><a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create Admin User</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Orders Management
                                </a>
                                <ul class="dropdown-menu">
                                  <li><a class="dropdown-item" asp-controller="Inquiry" asp-action="Index">Inquiries</a></li>
                                  <li><a class="dropdown-item" asp-controller="Order" asp-action="Index">Orders</a></li>
                                </ul>
                            </li>
                        }
                        <li>
                            @if(ShoppingCartService.CartCount() == 0)
                            {
                                <a href="#" class="nav-link">
                                    <i class="fa-solid fa-cart-shopping"></i> 0
                                </a>
                            }
                            else
                            {
                                <a asp-controller="Cart" asp-action="Index" class="nav-link">
                                    <i class="fa-solid fa-cart-shopping"></i> (@ShoppingCartService.CartCount())
                                </a>
                            }
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial"/>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer mt-auto py-3 bg-dark">
        <div class="container text-light">
            &copy; 2023 - RockyShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>   
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @*<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <!-- Syncfusion ASP.NET Core controls scripts -->
    <script src="https://cdn.syncfusion.com/ej2/21.1.35/dist/ej2.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

     <!-- Syncfusion ASP.NET Core Script Manager -->
    <ejs-scripts></ejs-scripts>
</body>
</html>

RockyShop/Views/Shared/_Notifications.cshtml
@using RockyShop.Utility.Utilities;

@{
	string success = (string)TempData[Constants.NotificationSuccess];
	string error = (string)TempData[Constants.NotificationError];
	if(success != null || error != null)
	{
		<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		@if(success != null)
		{
			<script>
				toastr.success('@success');
			</script>
		}
		else
		{
			<script>
				toastr.error('@error');
			</script>
		}
	}
}

RockyShop/Views/Shared/_ProductCard.cshtml
@model RockyShop.Model.Models.Product

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(" ", "_")">
    <!-- Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-header bg-dark text-light px-3 pt-3 pb-1">
            <div class="row">
                <div class="col-7"><label class="float-start">@Model.Name</label></div>
                <div class="col-5"><label class="float-end"><span class="text-warning h5">@(Model.Price.ToString("c"))</span> / sqft</label></div>
            </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge bg-primary p-2 border w-100" style="background-color:lavenderblush">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge bg-success p-2 border w-100" style="background-color:aliceblue">@Model.ApplicationType.Name</span>
            </div>
        <div class="col-12 pt-2" style="font-size:13px; text-align:justify" >
            <p>@Model.ShortDescription</p>
        </div>
        <div class="col-12 p-1">
            <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">View Details</a>
        </div>
        </div>
    </div>
</div>